### PR TITLE
feat: Added Coralogix exporter

### PR DESCRIPTION
**Pull request by cpheps**
### Proposed Change
Added the [Coralogix Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/coralogixexporter)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

### CODE REVIEW

**Review by BinaryFissionGames — APPROVED** [review]

**Comment by schmikei** [comment]
Looks like a licensing issue? Something to look into before merging for sure

**Comment by cpheps** [comment]
Added issue to the library to add a license.

coralogix/opentelemetry-cx-protobuf-api/issues/2

**Comment by cpheps** [comment]
Got approval from @jmwilliams89 to bypass the license check on this as it was accepted by OTel as safe. Will remove the exception if a license is added.

**Review by schmikei — APPROVED** [review]
SGTM 👍

**Pull request merged**
